### ISSUE TITLE
[Feature]: Giving the Option to place, text on the lines/arrows

### ISSUE THREAD

**Issue by Isaac-rise** [ElsaTam/obsidian-extended-graph#15]
**Is your feature request related to a problem? Please describe.**
If you wanna show a process, and wanna show the name of the precess. To change a information into a other one for example, it would be cool to separate thinks 

**Describe the solution you'd like**
Much more easy would be to just change the shape of a marble to a square, rectangle, square. 

**Describe alternatives you've considered**
just changing the colors of a marble is enough in the most cases I think so.

**Additional context**
It would be cool if there would be a css class to change the shape of a marble into an other, so that I can automize  the shaping. A other way could be to improve the group section in graph view in general. I will create a feature request for showing several folders in one graph view too. But this also could be solved by a better group section. 
In this group section you then could setup everything. Which shape shall the object out of one folder have, do they shall have borders in a specific color, which color shall the core have, shall the lines to specific objects be special (dotted, dashed, waved, colored)

Box on Line:
![Image](https://github.com/user-attachments/assets/46a05c0c-7749-4fe3-bfdc-679ceff53e1e)

**Comment by ElsaTam** [comment]
Regarding the shapes, the feature already exists: https://github.com/ElsaTam/obsidian-extended-graph/wiki/Node-Shapes

Regarding the text, there is an existing plugin that already does that: https://github.com/natefrisch01/Graph-Link-Types
Though I don't know how well mine and this one interact with each others. But since it's already something possible from another community plugin, this feature will have a low priority. But I will probably consider it at some point :)

**Comment by Isaac-rise** [comment]
Yes I noticed later.

**Comment by ElsaTam** [comment]
Underline is unfortunately the thing I would consider doing last, only if it's really needed. See this comment for more info: https://github.com/ElsaTam/obsidian-extended-graph/issues/76#issuecomment-2956612347

But I've added some CSS customization which should be available in the next release (the CSS bridge is one of the beta feature):
- Padding
- Border width
- Border color
- Background color
- Radius

So for example, you could do something like this:

![Image](https://github.com/user-attachments/assets/18cfb598-478f-4e4f-8930-27fa5a2b9e07)

That's the corresponding CSS. It's just for the example, it's definitively not pretty
```css
/* Default for all links */
.graph-view.link-text {
    border-width: 2px;
}

/* Or you can specify based on source or target (data attributes contain the full path) */
.graph-view.link-text[data-source*="P1"] {
    background-color: red;
}

.graph-view.link-text[data-source*="Lewis Hunter"] {
    border-width: 5px;
    border-color: cyan;
    padding: 5px;
}

.graph-view.link-text[data-source*="Marley Mills"] {
    border-color: orange;
    padding: 1px 5px;
    border-radius: 5px;
}

.graph-view.link-text[data-source*="Multiple"] {
    border-width: 2px;
    padding: 1px 5px;
    border-radius: 5px;
}

.graph-view.link-text[data-source*="Ruth Shaw"] {
    font-family: Papyrus;
    font-weight: 900;
}

.graph-view.link-text[data-target*="Lewis Hunter"] {
    background-color: rgba(0, 238, 255, 0.178);
    border-width: 0;
}
```

**Comment by ElsaTam** [comment]
So the left one most would only require that:
```css
.graph-view.link-text {
    border-width: 2px;
    padding: 1px 5px;
    border-radius: 5px;
}
```
I'll let you know once it's available in the next beta release :)

And yeah, LaTeX is great but not supported by the graphics library. That's a shame because someone asked on day to put latex equations instead of images, and render them in the nodes (I guess they are learning maths). I would have been really useful, especially to custom text.
